name: app_4
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.4.01+15

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  nfc_manager: ^3.2.0
  flutter_riverpod: ^2.0.2
  upgrader: ^4.9.0
  flutter_launcher_icons: ^0.10.0
  sqflite: ^2.1.0+1
  http: ^0.13.5
  connectivity_plus: ^3.0.2
  shared_preferences: ^2.0.15
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/icon.jpg"
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/menu.png
    - assets/images/valid.png
    - assets/images/invalid.png
    - assets/images/dropdown.png
    - assets/images/error.png
    - assets/images/scan.png
    - assets/images/en.png
    - assets/images/pt.png
    - assets/images/spinner.gif
    - assets/images/overlayCircles.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu_regular.ttf
        - asset: assets/fonts/ubuntu_bold.ttf
          weight: 400
